# Generated by Django 4.0 on 2021-12-13 22:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_post_comments_count_remove_post_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=200, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
    ]
